name: ben_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  camerawesome: ^1.4.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^11.1.4
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
