// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_recette.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform.name} - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDph9yo4OvrchyIP1WeSpufOKFxl_TuftI',
    appId: '1:768042519033:web:9c7b5ef432b39af6b81528',
    messagingSenderId: '768042519033',
    projectId: 'benapp-dev',
    authDomain: 'benapp-dev.firebaseapp.com',
    storageBucket: 'benapp-dev.appspot.com',
    measurementId: 'G-ZCCGGG1830',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTng-QbS9gJDSjn6oa7bmvxLqEdsy0ro',
    appId: '1:768042519033:android:8a0944503fa8d616b81528',
    messagingSenderId: '768042519033',
    projectId: 'benapp-dev',
    storageBucket: 'benapp-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWHDUNstw0sd48TZ6a6tTzLsw9GmsfbM',
    appId: '1:768042519033:ios:f70ebb34fe975105b81528',
    messagingSenderId: '768042519033',
    projectId: 'benapp-dev',
    storageBucket: 'benapp-dev.appspot.com',
    iosBundleId: 'fr.app.ben.benapp.dev',
  );
}
