// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform.name} - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKz5NW7wlLTohscnoX3lsPjdWiW4wCEd4',
    appId: '1:156253621348:web:9072aeea4a11371994e371',
    messagingSenderId: '156253621348',
    projectId: 'bureaudetudebenapp',
    authDomain: 'bureaudetudebenapp.firebaseapp.com',
    storageBucket: 'bureaudetudebenapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWa3jjNzJ_zWDjk0mhpt_aCqmW9PEa0QU',
    appId: '1:156253621348:android:77cbc28374ad7a9094e371',
    messagingSenderId: '156253621348',
    projectId: 'bureaudetudebenapp',
    storageBucket: 'bureaudetudebenapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtZLBn9ygCOfWVjSAUTLAdeRyUB7GAQ8s',
    appId: '1:156253621348:ios:a73199837447655294e371',
    messagingSenderId: '156253621348',
    projectId: 'bureaudetudebenapp',
    storageBucket: 'bureaudetudebenapp.appspot.com',
    iosBundleId: 'fr.app.ben.benapp',
  );
}
